---
title: "Results Notebook"
output:
  html_document:
    df_print: pdf
---

<!--

*Run* by pressing *Ctrl+Shift+Enter*. 
*Insert Chunk* by pressing *Ctrl+Alt+I*.

-->


```{r}
library(ggplot2)
library(scales)
library(tidyverse)
```

number of iterations per bar: 10000


```{r}
selection = read.csv("../results/06_showcase_results.csv") 

selection$success <- selection$tall_brown - selection$brown_tall

levels(selection$sd_brown) <- c("σ brown=0.1","σ brown=0.2")
levels(selection$sd_tall) <- c("σ big=0.25","σ big=0.3")
```


# Combined graph

```{r}

# New facet label names for supp variable
brown_names <- c("σ brown=0.1"="sigma[brown]==0.1", "σ brown=0.2" = "sigma[brown] == 0.2")
big_names <- c("σ big=0.25" = "sigma[big]==0.25", "σ big=0.3" = "sigma[big]==0.3")

# Create the plot
#p + facet_grid(
#  dose ~ supp, 
#  labeller = labeller(dose = dose.labs, supp = supp.labs)
#  )


combined_plot = selection %>%
  ggplot(aes(x = as.factor(n_obj))) +
  geom_col(aes(y = success, fill = as.factor(theta)), position = "dodge") +
  geom_col(aes(y = -reverse_scale*proportion_exceptions, fill = as.factor(-theta)), position = "dodge") +
  facet_grid(sd_brown ~ sd_tall, scales="free", labeller = labeller(sd_brown= as_labeller(brown_names,  label_parsed),sd_tall= as_labeller(big_names,  label_parsed)))+
  ylab("difference in mean success probability  /\n proportion of exceptions") +
  xlab("number of objects in context")  + #scale_fill_brewer(palette="Set1", name = "semantic threshold") +
  geom_hline( yintercept = 0) +
  expand_limits(y = c(-0.35*reverse_scale,0.18) ) +
  scale_y_continuous( minor_breaks=c(-0.3*reverse_scale, -0.25*reverse_scale, -0.2*reverse_scale, -0.15*reverse_scale, -0.1*reverse_scale, -0.05*reverse_scale,
                                     0.025, 0.05, 0.075, 0.1, 0.125, 0.15, 0.175),
                      breaks = c(-0.3*reverse_scale,-0.2*reverse_scale,-0.1*reverse_scale,0.05,0,0.1,0.15),
                      labels = c("30\\%", "20\\%","10\\%","0.05","0","0.1","0.15")) +
  scale_fill_manual(values=c("#7a7a7a","#aa8989","#cdcdff","#89aa89","#00aa00","#0000ff","#aa0000","#000000"), breaks = c("0.2", "0.4", "0.6","0.8"), name = "semantic threshold") +
  theme_bw() +
  theme(legend.position="bottom")

show(combined_plot)
```
