---
title: "Results Notebook"
output: html_notebook
---


```{r}
options(encoding = "UTF-8")
source('~/adjective_order/results/01_referential_success_k-percent_semantics.r')
```


```{r}

iterations = 5000
results = rbind(
  get_outcomes(iterations, n_obj = 4, sd_brown = 0.1, sd_tall = 0.25, theta = 0.5),
  get_outcomes(iterations, n_obj = 6, sd_brown = 0.1, sd_tall = 0.25, theta = 0.5),
  get_outcomes(iterations, n_obj = 8, sd_brown = 0.1, sd_tall = 0.25, theta = 0.5),
  get_outcomes(iterations, n_obj = 4, sd_brown = 0.2, sd_tall = 0.3, theta = 0.5),
  get_outcomes(iterations, n_obj = 6, sd_brown = 0.2, sd_tall = 0.3, theta = 0.5),
  get_outcomes(iterations, n_obj = 8, sd_brown = 0.2, sd_tall = 0.3, theta = 0.5),
  get_outcomes(iterations, n_obj = 4, sd_brown = 0.1, sd_tall = 0.25, theta = 0.7),
  get_outcomes(iterations, n_obj = 6, sd_brown = 0.1, sd_tall = 0.25, theta = 0.7),
  get_outcomes(iterations, n_obj = 8, sd_brown = 0.1, sd_tall = 0.25, theta = 0.7),
  get_outcomes(iterations, n_obj = 4, sd_brown = 0.2, sd_tall = 0.3, theta = 0.7),
  get_outcomes(iterations, n_obj = 6, sd_brown = 0.2, sd_tall = 0.3, theta = 0.7),
  get_outcomes(iterations, n_obj = 8, sd_brown = 0.2, sd_tall = 0.3, theta = 0.7),
  # 
  get_outcomes(iterations, n_obj = 4, sd_brown = 0.1, sd_tall = 0.25, theta = 0.4),
  get_outcomes(iterations, n_obj = 6, sd_brown = 0.1, sd_tall = 0.25, theta = 0.4),
  get_outcomes(iterations, n_obj = 8, sd_brown = 0.1, sd_tall = 0.25, theta = 0.4),
  get_outcomes(iterations, n_obj = 4, sd_brown = 0.2, sd_tall = 0.3, theta = 0.4),
  get_outcomes(iterations, n_obj = 6, sd_brown = 0.2, sd_tall = 0.3, theta = 0.4),
  get_outcomes(iterations, n_obj = 8, sd_brown = 0.2, sd_tall = 0.3, theta = 0.4),
  get_outcomes(iterations, n_obj = 4, sd_brown = 0.1, sd_tall = 0.25, theta = 0.8),
  get_outcomes(iterations, n_obj = 6, sd_brown = 0.1, sd_tall = 0.25, theta = 0.8),
  get_outcomes(iterations, n_obj = 8, sd_brown = 0.1, sd_tall = 0.25, theta = 0.8),
  get_outcomes(iterations, n_obj = 4, sd_brown = 0.2, sd_tall = 0.3, theta = 0.8),
  get_outcomes(iterations, n_obj = 6, sd_brown = 0.2, sd_tall = 0.3, theta = 0.8),
  get_outcomes(iterations, n_obj = 8, sd_brown = 0.2, sd_tall = 0.3, theta = 0.8)
)
show(results)

selection = select(filter(results, context_types == "all"), -sum_success_prob) %>% 
  spread(key = ordering, value = mean_success) 

selection$group <- paste(selection$n_obj, selection$sd_brown, selection$sd_tall)

selection %>% ggplot( aes(x=as.factor(theta), y= tall_brown - brown_tall, group = group, col=group)) + geom_point() + geom_line(linetype = "dashed")

```

